name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Check installed ajv version
        run: npm list ajv

      - name: Check installed ajv-keywords version
        run: npm list ajv-keywords

      - name: Create environment file
        run: |
          echo "HOST=localhost" >> .env
          echo "PORT=1337" >> .env
          echo "DATABASE_CLIENT=postgres" >> .env
          echo "DATABASE_HOST=localhost" >> .env
          echo "DATABASE_PORT=5432" >> .env
          echo "DATABASE_NAME=strapi" >> .env
          echo "DATABASE_USERNAME=strapi" >> .env
          echo "DATABASE_PASSWORD=strapi" >> .env
          echo "ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Build Strapi
        run: npm run build

      # - name: Run tests
      #   run: npm test

      - name: Debug - Print npm environment details
        if: failure()  # This step will run only if the previous steps fail
        run: |
          echo "NPM Version:"
          npm --version
          echo "Node Version:"
          node --version
          echo "List installed packages:"
          npm list --depth=0
