name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: List installed packages
        run: npm list --depth=0

      - name: Set up environment variables
        run: |
          echo "HOST=localhost" >> .env
          echo "PORT=1337" >> .env
          echo "DATABASE_CLIENT=postgres" >> .env
          echo "DATABASE_HOST=localhost" >> .env
          echo "DATABASE_PORT=5432" >> .env
          echo "DATABASE_NAME=strapi" >> .env
          echo "DATABASE_USERNAME=strapi" >> .env
          echo "DATABASE_PASSWORD=strapi" >> .env
          echo "ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Debug - Print .env file
        run: cat .env

      - name: Debug - Print environment variables
        run: env

      - name: Debug - Print npm version
        run: npm --version

      - name: Debug - Print Node.js version
        run: node --version

      - name: Build Strapi
        run: npm run build

      - name: Run tests
        run: npm test
